### ISSUE TITLE
Crontab not working correctly

### ISSUE THREAD

**Issue by geaz** [shneezin/breitbandmessung#2]
First of all, thanks for the project!

I have a problem with the docker container. This is my config:

```
[Docker Config]
timezone=Europe/Berlin
crontab=0 */2 * * *
run_once=false
run_on_startup=false
```

Unfortunately the run_once flag is just ignored as it seems. According to the entrypoint.sh I would expect an output info about setting the crontab.

![grafik](https://user-images.githubusercontent.com/1579505/155477113-8ac923bc-fdde-49eb-8600-5e848510707c.png)

Instead the script just starts the measurement and terminates the container afterwards. Anything I misconfigured?
Here the console output:

![grafik](https://user-images.githubusercontent.com/1579505/155477223-45fe7772-941b-4516-8b38-d1fd483f4c3f.png)

Thanks for the help!

**Comment by Shnezzin** [comment]
Thank you for the praise.

Regarding your problem, I was able to reproduce the error.
I assume that there are spaces in your configuration, which is why the configuration can not be read correctly.
I have adjusted the reading of the configuration. Could you test it again, if it now works correctly?

The container is still being created. In about 20 minutes the current version should be available at docker hub.

**Comment by geaz** [comment]
Works like a charm now. Thank you!
